services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Readspeaker\ReadspeakerServices\:
    resource: '../Classes/Controller/ReadspeakerServicesController.php'

  Readspeaker\ReadspeakerServices\Controller\ReadspeakerServicesController:
    public: true

  Readspeaker\ReadspeakerServices\ViewHelpers\WebreaderbuttonViewHelper:
    public: true
